### ISSUE TITLE
add new model

### ISSUE THREAD

**Issue by BatunaAz** [dptole/laravel-survey#17]
Hello, thank you for your team work. 
I have one issue but its just mine. 
I need add customer to this project, It helps me survey has many customer and answer need to save with customer's id 
How can i customer_id for my saveAnswer API.

**Comment by dptole** [comment]
Hi @BatunaAz thanks for using my repo :)

In order to save the user id (customer_id) you would have to:

1) Create a new migration using `php artisan make:migration <FILENAME>` to add a new column to the table `answers_sessions`. This column needs to be a nullable foreign key to the table users;
2) Update the method `APIController->getSessionId()` to read the `customer_id` from `$request->user()` and send it to the next step;
3) Update the method `AnswersSessions::createSession()` to receive the `customer_id`.

The call `$request->user()` returns null if the user is not logged in, otherwise a App/User instance will be returned.

This app is still requires more polishing but I'm busy at the moment.

Hope it helps!

**Comment by BatunaAz** [comment]
Thanks a lot.
