### ISSUE TITLE
Redirect to laravel

### ISSUE THREAD

**Issue by shaan207** [dptole/laravel-survey#3]
I tried to remove /laravel from url. But when open the survey (public-survey) to fill it it gives me a message of "try again later" and redirects to mydomain.com/laravel/. I think it is redirecting it from somewhere in js. can you point it or resolve it?
Thank you.

**Comment by dptole** [comment]
@shaan207 thanks for opening this issue

The system is a bit messy at the moment but you can check the file https://github.com/dptole/laravel-survey/blob/master/routes/web.php and change the routes

My intention was to place the whole system under "/laravel" because it should behave as a subsystem of "https://dptole.ngrok.io/"

On this specific line you can change the default prefix https://github.com/dptole/laravel-survey/blob/master/routes/web.php#L16 **(though you might have to change code everywhere the text "/laravel" is present in the context of a redirect)**

```php
Route::group(['prefix' => 'laravel', 'middleware' => ['google_recaptcha', 'email_checkdnsrr']], function() {
  # ...
});
```

By replacing `'prefix' => 'laravel'` with `'prefix' => 'xxx'` you are realocating the system to "/xxx" instead of "/laravel"
